// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.14.0
// source: foxglove/FrameTransform.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../google/protobuf/timestamp";
import { Quaternion } from "./Quaternion";
import { Vector3 } from "./Vector3";

export const protobufPackage = "foxglove";

/** A transform between two reference frames in 3D space */
export interface FrameTransform {
  /** Timestamp of transform */
  timestamp:
    | Date
    | undefined;
  /** Name of the parent frame */
  parentFrameId: string;
  /** Name of the child frame */
  childFrameId: string;
  /** Translation component of the transform */
  translation:
    | Vector3
    | undefined;
  /** Rotation component of the transform */
  rotation: Quaternion | undefined;
}

function createBaseFrameTransform(): FrameTransform {
  return { timestamp: undefined, parentFrameId: "", childFrameId: "", translation: undefined, rotation: undefined };
}

export const FrameTransform: MessageFns<FrameTransform> = {
  encode(message: FrameTransform, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestamp !== undefined) {
      Timestamp.encode(toTimestamp(message.timestamp), writer.uint32(10).fork()).join();
    }
    if (message.parentFrameId !== "") {
      writer.uint32(18).string(message.parentFrameId);
    }
    if (message.childFrameId !== "") {
      writer.uint32(26).string(message.childFrameId);
    }
    if (message.translation !== undefined) {
      Vector3.encode(message.translation, writer.uint32(34).fork()).join();
    }
    if (message.rotation !== undefined) {
      Quaternion.encode(message.rotation, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FrameTransform {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFrameTransform();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.timestamp = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.parentFrameId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.childFrameId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.translation = Vector3.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.rotation = Quaternion.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FrameTransform {
    return {
      timestamp: isSet(object.timestamp) ? fromJsonTimestamp(object.timestamp) : undefined,
      parentFrameId: isSet(object.parentFrameId) ? globalThis.String(object.parentFrameId) : "",
      childFrameId: isSet(object.childFrameId) ? globalThis.String(object.childFrameId) : "",
      translation: isSet(object.translation) ? Vector3.fromJSON(object.translation) : undefined,
      rotation: isSet(object.rotation) ? Quaternion.fromJSON(object.rotation) : undefined,
    };
  },

  toJSON(message: FrameTransform): unknown {
    const obj: any = {};
    if (message.timestamp !== undefined) {
      obj.timestamp = message.timestamp.toISOString();
    }
    if (message.parentFrameId !== "") {
      obj.parentFrameId = message.parentFrameId;
    }
    if (message.childFrameId !== "") {
      obj.childFrameId = message.childFrameId;
    }
    if (message.translation !== undefined) {
      obj.translation = Vector3.toJSON(message.translation);
    }
    if (message.rotation !== undefined) {
      obj.rotation = Quaternion.toJSON(message.rotation);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FrameTransform>, I>>(base?: I): FrameTransform {
    return FrameTransform.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FrameTransform>, I>>(object: I): FrameTransform {
    const message = createBaseFrameTransform();
    message.timestamp = object.timestamp ?? undefined;
    message.parentFrameId = object.parentFrameId ?? "";
    message.childFrameId = object.childFrameId ?? "";
    message.translation = (object.translation !== undefined && object.translation !== null)
      ? Vector3.fromPartial(object.translation)
      : undefined;
    message.rotation = (object.rotation !== undefined && object.rotation !== null)
      ? Quaternion.fromPartial(object.rotation)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
