// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.14.0
// source: foxglove/FrameTransforms.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { FrameTransform } from "./FrameTransform";

export const protobufPackage = "foxglove";

/** An array of FrameTransform messages */
export interface FrameTransforms {
  /** Array of transforms */
  transforms: FrameTransform[];
}

function createBaseFrameTransforms(): FrameTransforms {
  return { transforms: [] };
}

export const FrameTransforms: MessageFns<FrameTransforms> = {
  encode(message: FrameTransforms, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.transforms) {
      FrameTransform.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FrameTransforms {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFrameTransforms();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.transforms.push(FrameTransform.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FrameTransforms {
    return {
      transforms: globalThis.Array.isArray(object?.transforms)
        ? object.transforms.map((e: any) => FrameTransform.fromJSON(e))
        : [],
    };
  },

  toJSON(message: FrameTransforms): unknown {
    const obj: any = {};
    if (message.transforms?.length) {
      obj.transforms = message.transforms.map((e) => FrameTransform.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FrameTransforms>, I>>(base?: I): FrameTransforms {
    return FrameTransforms.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FrameTransforms>, I>>(object: I): FrameTransforms {
    const message = createBaseFrameTransforms();
    message.transforms = object.transforms?.map((e) => FrameTransform.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
