// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.14.0
// source: foxglove/GeoJSON.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "foxglove";

/** GeoJSON data for annotating maps */
export interface GeoJSON {
  /** GeoJSON data encoded as a UTF-8 string */
  geojson: string;
}

function createBaseGeoJSON(): GeoJSON {
  return { geojson: "" };
}

export const GeoJSON: MessageFns<GeoJSON> = {
  encode(message: GeoJSON, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.geojson !== "") {
      writer.uint32(10).string(message.geojson);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GeoJSON {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGeoJSON();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.geojson = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GeoJSON {
    return { geojson: isSet(object.geojson) ? globalThis.String(object.geojson) : "" };
  },

  toJSON(message: GeoJSON): unknown {
    const obj: any = {};
    if (message.geojson !== "") {
      obj.geojson = message.geojson;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GeoJSON>, I>>(base?: I): GeoJSON {
    return GeoJSON.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GeoJSON>, I>>(object: I): GeoJSON {
    const message = createBaseGeoJSON();
    message.geojson = object.geojson ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
