// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.14.0
// source: foxglove/SceneEntityDeletion.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "foxglove";

/** Command to remove previously published entities */
export interface SceneEntityDeletion {
  /** Timestamp of the deletion. Only matching entities earlier than this timestamp will be deleted. */
  timestamp:
    | Date
    | undefined;
  /** Type of deletion action to perform */
  type: SceneEntityDeletion_Type;
  /** Identifier which must match if `type` is `MATCHING_ID`. */
  id: string;
}

/** An enumeration indicating which entities should match a SceneEntityDeletion command */
export enum SceneEntityDeletion_Type {
  /** MATCHING_ID - Delete the existing entity on the same topic that has the provided `id` */
  MATCHING_ID = 0,
  /** ALL - Delete all existing entities on the same topic */
  ALL = 1,
  UNRECOGNIZED = -1,
}

export function sceneEntityDeletion_TypeFromJSON(object: any): SceneEntityDeletion_Type {
  switch (object) {
    case 0:
    case "MATCHING_ID":
      return SceneEntityDeletion_Type.MATCHING_ID;
    case 1:
    case "ALL":
      return SceneEntityDeletion_Type.ALL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SceneEntityDeletion_Type.UNRECOGNIZED;
  }
}

export function sceneEntityDeletion_TypeToJSON(object: SceneEntityDeletion_Type): string {
  switch (object) {
    case SceneEntityDeletion_Type.MATCHING_ID:
      return "MATCHING_ID";
    case SceneEntityDeletion_Type.ALL:
      return "ALL";
    case SceneEntityDeletion_Type.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

function createBaseSceneEntityDeletion(): SceneEntityDeletion {
  return { timestamp: undefined, type: 0, id: "" };
}

export const SceneEntityDeletion: MessageFns<SceneEntityDeletion> = {
  encode(message: SceneEntityDeletion, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestamp !== undefined) {
      Timestamp.encode(toTimestamp(message.timestamp), writer.uint32(10).fork()).join();
    }
    if (message.type !== 0) {
      writer.uint32(16).int32(message.type);
    }
    if (message.id !== "") {
      writer.uint32(26).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SceneEntityDeletion {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSceneEntityDeletion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.timestamp = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SceneEntityDeletion {
    return {
      timestamp: isSet(object.timestamp) ? fromJsonTimestamp(object.timestamp) : undefined,
      type: isSet(object.type) ? sceneEntityDeletion_TypeFromJSON(object.type) : 0,
      id: isSet(object.id) ? globalThis.String(object.id) : "",
    };
  },

  toJSON(message: SceneEntityDeletion): unknown {
    const obj: any = {};
    if (message.timestamp !== undefined) {
      obj.timestamp = message.timestamp.toISOString();
    }
    if (message.type !== 0) {
      obj.type = sceneEntityDeletion_TypeToJSON(message.type);
    }
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SceneEntityDeletion>, I>>(base?: I): SceneEntityDeletion {
    return SceneEntityDeletion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SceneEntityDeletion>, I>>(object: I): SceneEntityDeletion {
    const message = createBaseSceneEntityDeletion();
    message.timestamp = object.timestamp ?? undefined;
    message.type = object.type ?? 0;
    message.id = object.id ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
