// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.14.0
// source: foxglove/TextAnnotation.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../google/protobuf/timestamp";
import { Color } from "./Color";
import { Point2 } from "./Point2";

export const protobufPackage = "foxglove";

/** A text label on a 2D image */
export interface TextAnnotation {
  /** Timestamp of annotation */
  timestamp:
    | Date
    | undefined;
  /**
   * Bottom-left origin of the text label in 2D image coordinates (pixels).
   * The coordinate uses the top-left corner of the top-left pixel of the image as the origin.
   */
  position:
    | Point2
    | undefined;
  /** Text to display */
  text: string;
  /** Font size in pixels */
  fontSize: number;
  /** Text color */
  textColor:
    | Color
    | undefined;
  /** Background fill color */
  backgroundColor: Color | undefined;
}

function createBaseTextAnnotation(): TextAnnotation {
  return {
    timestamp: undefined,
    position: undefined,
    text: "",
    fontSize: 0,
    textColor: undefined,
    backgroundColor: undefined,
  };
}

export const TextAnnotation: MessageFns<TextAnnotation> = {
  encode(message: TextAnnotation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestamp !== undefined) {
      Timestamp.encode(toTimestamp(message.timestamp), writer.uint32(10).fork()).join();
    }
    if (message.position !== undefined) {
      Point2.encode(message.position, writer.uint32(18).fork()).join();
    }
    if (message.text !== "") {
      writer.uint32(26).string(message.text);
    }
    if (message.fontSize !== 0) {
      writer.uint32(33).double(message.fontSize);
    }
    if (message.textColor !== undefined) {
      Color.encode(message.textColor, writer.uint32(42).fork()).join();
    }
    if (message.backgroundColor !== undefined) {
      Color.encode(message.backgroundColor, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TextAnnotation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTextAnnotation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.timestamp = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.position = Point2.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.fontSize = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.textColor = Color.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.backgroundColor = Color.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TextAnnotation {
    return {
      timestamp: isSet(object.timestamp) ? fromJsonTimestamp(object.timestamp) : undefined,
      position: isSet(object.position) ? Point2.fromJSON(object.position) : undefined,
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      fontSize: isSet(object.fontSize) ? globalThis.Number(object.fontSize) : 0,
      textColor: isSet(object.textColor) ? Color.fromJSON(object.textColor) : undefined,
      backgroundColor: isSet(object.backgroundColor) ? Color.fromJSON(object.backgroundColor) : undefined,
    };
  },

  toJSON(message: TextAnnotation): unknown {
    const obj: any = {};
    if (message.timestamp !== undefined) {
      obj.timestamp = message.timestamp.toISOString();
    }
    if (message.position !== undefined) {
      obj.position = Point2.toJSON(message.position);
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.fontSize !== 0) {
      obj.fontSize = message.fontSize;
    }
    if (message.textColor !== undefined) {
      obj.textColor = Color.toJSON(message.textColor);
    }
    if (message.backgroundColor !== undefined) {
      obj.backgroundColor = Color.toJSON(message.backgroundColor);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TextAnnotation>, I>>(base?: I): TextAnnotation {
    return TextAnnotation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TextAnnotation>, I>>(object: I): TextAnnotation {
    const message = createBaseTextAnnotation();
    message.timestamp = object.timestamp ?? undefined;
    message.position = (object.position !== undefined && object.position !== null)
      ? Point2.fromPartial(object.position)
      : undefined;
    message.text = object.text ?? "";
    message.fontSize = object.fontSize ?? 0;
    message.textColor = (object.textColor !== undefined && object.textColor !== null)
      ? Color.fromPartial(object.textColor)
      : undefined;
    message.backgroundColor = (object.backgroundColor !== undefined && object.backgroundColor !== null)
      ? Color.fromPartial(object.backgroundColor)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
